name: .NET CI (build + format)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-format:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "DigiMediaStore.sln"

      - name: Build
        run: dotnet build "DigiMediaStore.sln" --configuration Release --no-restore

      - name: Check formatting
        run: dotnet format "DigiMediaStore.sln" --verify-no-changes --verbosity diagnostic

      - name: Test
        run: dotnet test "DigiMediaStore.sln" --configuration Release --no-build


